version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SchoolAdminDb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d SchoolAdminDb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - school-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s

  backend:
    image: school-admin-backend:latest
    environment:
      - NODE_ENV=production
      - DATABASE_URL="postgresql://postgres:postgres@localhost:5400/SchoolAdminDb"
      - JWT_SECRET="RnH8RpXMAC63SvGLanBIorNXBNbnx1Gl"
      - TEACHER_PASSWORD="n)dUs5zPSAc>Qn9"
      - ADMIN_PASSWORD="SpwdyBOqu"
    networks:
      - school-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s

  frontend:
    image: school-admin-frontend:latest
    environment:
      - NEXT_PUBLIC_API_URL=http://45.149.235.33/api
      - INTERNAL_API_URL=http://backend:5000/api
    networks:
      - school-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - school-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  pgdata:
    driver: local

networks:
  school-network:
    driver: overlay
    attachable: true

