version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SchoolAdminDb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d SchoolAdminDb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - school-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.database == true
      restart_policy:
        condition: on-failure
        delay: 10s

  backend:
    image: school-admin-backend:latest  # Предварительно собранный образ
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/SchoolAdminDb
    networks:
      - school-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.backend == true
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s

  frontend:
    image: school-admin-frontend:latest  # Предварительно собранный образ
    environment:
      - NEXT_PUBLIC_API_URL=https://your-domain.com/api   
      - INTERNAL_API_URL=http://backend:5000/api
    networks:
      - school-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.frontend == true
      restart_policy:
        condition: on-failure
        delay: 5s

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - school-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

volumes:
  pgdata:
    driver: local

networks:
  school-network:
    driver: overlay
    attachable: true
